### ISSUE TITLE
알타님이 만드신 바코드 트리거를 적용했더니 경로가 잘못된 에러가 나옵니다

### ISSUE THREAD

**Issue by LeePC** [iDoodler-DS/EUDEditor#13]
```euddraft 0.9.6.1 : Simple eudplib plugin system
 - This program follows MIT License. See license.txt
 - Press SHIFT to force check update while opening euddraft.
 - Daemon mode. Ctrl+C to quit. R to recompile (windows only)


[[Updating on 2022-07-09 17:46:00]]
---------- Loading plugins... ----------
맵 C:\Users\ㅌㅌㅌ\Documents\StarCraft\Maps\Download\SCVSurvival-Original.scx 불러오는 중
Loading plugin EUDEditor.py...
Loading plugin TriggerEditor.eps...
[epScript] "TriggerEditor.eps" 컴파일 중...
[epScript] "BGMPlayer.eps" 컴파일 중...
Loading plugin dataDumper...
 - Loading file "C:\Users\ㅌㅌㅌ\Documents\EUD\EUD.EditorSE2.0.18.0.1\Data\temp\RequireData"...
Loading plugin noAirCollision...
Loading plugin unlimiter...
Loading plugin eudTurbo...
Loading plugin barcode...
                          *                                         *
        *                                        *
                        [[ freeze activated ]]
                                  *                       *
                *                                                          *
--------- Injecting plugins... ---------
Freeze - sectorSize disabled
C:\Users\ㅌㅌㅌ\Documents\StarCraft\Maps\Download\SCV키우기.scx에 저장 중...
==========================================
[Error] b'Temp' Traceback (most recent call last):
  File "C:\Users\ㅌㅌㅌ\Documents\EUD\EUD.EditorSE2.0.18.0.1\Data\eudplibdata\TriggerEditor.eps", line 119, in beforeTriggerExec
    }
  File "E:\P\lib\site-packages\eudplib-0.69.10-py3.10-win-amd64.egg\eudplib\core\mapdata\stringmap.py", line 80, in GetLocationIndex
  File "E:\P\lib\site-packages\eudplib-0.69.10-py3.10-win-amd64.egg\eudplib\core\mapdata\stringmap.py", line 47, in GetStringIndex
KeyError: b'Temp'

Done!```

고쳐주셨으면 하는 소망입니다

**Comment by armoha** [comment]
맵에 Temp라는 이름의 로케이션이 없다네요.
```
[Error] b'Temp' Traceback (most recent call last):
  File "C:\Users\ㅌㅌㅌ\Documents\EUD\EUD.EditorSE2.0.18.0.1\Data\eudplibdata\TriggerEditor.eps", line 119, in beforeTriggerExec
    }
```

**Comment by LeePC** [comment]
오 고맙습니다 고쳐졌습니다!!
